query getAffiliateSalesData($affiliateEmail: String) {
  getAffiliateSalesData(affiliateEmail: $affiliateEmail) {
    monthlyPerformance {
      month
      affiliateSales
      subAffiliatesSales
      affiliateSalesComission
      subAffiliatesSalesComission
    }
  }
}
