query getAffiliateByMail($affiliateMail: String) {
  getAffiliateByMail(affiliateMail: $affiliateMail)
    @context(provider: "avantivtexio.avanti-vtexio-boilerplate-backend") {
    affiliateId
    affiliateCode
    sponsor {
      affiliateId
      email
    }
    name
    cpf
    email
    gender
    address {
      postalCode
      street
      number
      neighborhood
      complement
      city
      state
    }
    phone
    status
  }
}
