query GetAffiliateOrdersInput($input: GetAffiliateOrdersInput) {
  getAffiliateOrders(input: $input)
    @context(provider: "vtexdayhackathon3.affiliates-program") {
    data {
      orderId
      orderDate
      orderTotalValue
      status
      affiliate {
        id
        name
        documentType
        document
        role
        amount
        commissionAmount
        chargeProcesssingFee
        chargebackLiable
      }
      sponsor {
        id
        name
        documentType
        document
        role
        amount
        commissionAmount
        chargeProcesssingFee
        chargebackLiable
      }
    }
  }
}
