query getAffiliates($input: GetAffiliatesInput) {
  getAffiliates(input: $input)
    @context(provider: "avantivtexio.affiliate-program") {
    data {
      affiliateId
      affiliateCode
      sponsor {
        affiliateId
        email
      }
      name
      cpf
      email
      gender
      address {
        postalCode
        street
        number
        neighborhood
        complement
        city
        state
      }
      phone
      status
      createdIn
    }
    pagination {
      page
      pageSize
      total
    }
  }
}
