query getAffiliateByCode($affiliateCode: String) {
  getAffiliateByCode(affiliateCode: $affiliateCode)
    @context(provider: "avantivtexio.affiliate-program") {
    affiliateId
    affiliateCode
    sponsor {
      affiliateId
      email
    }
    name
    cpf
    email
    gender
    address {
      postalCode
      street
      number
      neighborhood
      complement
      city
      state
    }
    phone
    status
    createdIn
  }
}
