query getAffiliateCode($code: String) {
  getAffiliateCode(code: $code)
    @context(provider: "avantivtexio.avanti-vtexio-boilerplate-backend") {
    code
    affiliateId
    expiresAt
  }
}
