query getSubAffiliatesData($input: GetSubAffiliatesDataInput) {
  getSubAffiliatesData(input: $input)
    @context(provider: "vtexdayhackathon3.affiliates-program") {
    name
    sold
    status
  }
}